config/urls.py
from ajax_select import urls as ajax_select_urls

from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("bishopric_tools.users.urls", namespace="users")),
    # Login
    path("accounts/", include("django.contrib.auth.urls")),
    # django-ajax-select url
    path("ajax_select/", include(ajax_select_urls)),
    # Your stuff: custom urls includes go here
    path("members/", include("people.urls")),
    path("talks/", include("events.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path("400/", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")},),
        path("403/", default_views.permission_denied, kwargs={"exception": Exception("Permission Denied")},),
        path("404/", default_views.page_not_found, kwargs={"exception": Exception("Page not Found")},),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

events/urls.py
from django.urls import path

from . import views

app_name = "talks"

urlpatterns = [
    path("<int:id>/", views.TalkDetail.as_view(), name="talk-detail"),
    path("<int:id>/pdf", views.TalkPdfDetail.as_view(), name="talk-pdf"),
    path("<int:id>/edit", views.TalkEdit.as_view(), name="talk-edit"),
    path("add/", views.TalkAdd.as_view(), name="add"),
    path("", views.TalkList.as_view(), name="list"),
]

events/models.py
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel


class Talk(TimeStampedModel):
    speaker = models.ForeignKey("people.Member", on_delete=models.CASCADE)
    date = models.DateField()
    topic = models.CharField(max_length=150, blank=True, null=True)
    time_range = models.CharField(max_length=10, blank=True, null=True)
    reference_materials = models.TextField("Reference Materials", blank=True, null=True)

    bishopric = models.TextField("Bishopric")
    order = models.IntegerField("Speaker Order", blank=True, null=True)

    def __str__(self):
        return "{} on {}".format(self.speaker.full_name, self.date)

    def get_absolute_url(self):
        return reverse("talks:talk-detail", args=[str(self.pk)])


class SacramentMeeting(models.Model):
    date = models.DateField()

    def __str__(self):
        return "Sacrament Meeting on {}".format(self.date)

events/forms.py
from ajax_select.fields import AutoCompleteSelectField
from crispy_forms.bootstrap import AppendedText
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Row, Column
from django import forms

from . import models


class TalkForm(forms.ModelForm):
    speaker = AutoCompleteSelectField("members", required=True, help_text=None, plugin_options={"minLength": 2})
    reference_materials = forms.CharField(
        label="Reference Materials", widget=forms.Textarea(attrs={"rows": 2}), required=False,
    )
    bishopric = forms.CharField(
        label="Bishopric",
        widget=forms.Textarea(attrs={"rows": 4}),
        # initial=models.Talk._meta.get_field("bishopric").default,
        required=True,
    )
    date = forms.DateField(input_formats=["%d %b %Y"],)

    class Meta:
        model = models.Talk
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        button = kwargs.pop("button", "Create Talk")
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", button))
        self.helper.form_id = "add-form"
        self.helper.layout = Layout(
            Row(
                Column("speaker", css_class="form-group col-6 mb-0"),
                AppendedText(
                    "date", '<i class="fa fa-calendar" aria-hidden="true"></i>', active=True, wrapper_class="col-6",
                ),
                css_class="form-row",
            ),
            Row(
                Column("time_range", css_class="form-group col-6 mb-0"),
                Column("order", css_class="form-group col-6 mb-0"),
                css_class="form-row",
            ),
            "topic",
            "reference_materials",
            "bishopric",
        )

events/views.py
from typing import Any, Dict

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from django_xhtml2pdf.views import PdfMixin

from . import models
from . import forms


class TalkDetail(DetailView):
    model = models.Talk
    slug_field = "id"
    slug_url_kwarg = "id"


class TalkPdfDetail(PdfMixin, TalkDetail):
    template_name = "events/pdf.html"


class TalkAdd(LoginRequiredMixin, CreateView):
    model = models.Talk
    form_class = forms.TalkForm

    def get_initial(self):
        init = super(TalkAdd, self).get_initial()
        # Copy the dictionary so we don't accidentally change a mutable dict
        initial = init.copy()
        initial["speaker"] = self.request.GET.get("member", None)
        return initial


class TalkEdit(LoginRequiredMixin, UpdateView):
    model = models.Talk
    form_class = forms.TalkForm
    slug_field = "id"
    slug_url_kwarg = "id"

    def get_form_kwargs(self) -> Dict[str, Any]:
        values = super(TalkEdit, self).get_form_kwargs()
        values["button"] = "Update Talk"
        return values

    def get_initial(self) -> Dict[str, Any]:
        init = super(TalkEdit, self).get_initial()
        # Copy the dictionary so we don't accidentally change a mutable dict
        initial = init.copy()
        # Reformat the date
        initial["date"] = self.model.date.strftime("%d %b %Y")
        # Return the initial values
        return initial


class TalkList(ListView):
    model = models.Talk

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.order_by("date", "order")
        return qs

events/templates/events/pdf.html
{% load staticfiles %}

<html lang=en>

<head>
	<title>{{ object.date|date:"Y-m-d"}} {{ object.speaker.full_name }}</title>
	<style type="text/css">
		@page {
			size: letter;
			margin: 1in;
		}
    .helv {
      font-family: Helvetica;
      font-size: 10px;
      font-style: normal;
      font-variant: small-caps;
    }
    .center {
      text-align: center;
    }
    img {
      display: block;
      margin-left: auto;
      margin-right: auto;
      width: 33%;
    }
		html, body {
			font-size: 12pt;
			line-height: 1.25;
			font-family: "Times New Roman", Times, serif;
		}
		body {
			text-align: justify;
			padding: 0 !important;
       		background: none !important;
		}
		h1 {
			margin-top: 1em;
			margin-bottom: 0em;
			page-break-before: auto !important;
			font-family: inherit !important;
			font-size: 1.5em;
		}
	</style>
</head>
<body>
  <img src="{% static 'images/179px-Logo_of_the_Church_of_Jesus_Christ_of_Latter-day_Saints.png' %}" class="center"><br>
  <p class="helv">
    BROOMFIELD FIRST WARD<br>
    BOULDER COLORADO STAKE
  </p>

  <p>
  {{ object.created|date:"d F Y" }}
  </p>

  <p>
  {{ object.speaker.full_name }}<br>
  {{ object.speaker.street1 }}<br>
  {% if object.speaker.street2 %}
  {{ object.speaker.street2 }}<br>
  {% endif %}
  Broomfield, CO 80020
  </p>

  <p>
    Dear {{ object.speaker.formal_name }},
  </p>
  <p>
    The Broomfield First Ward Bishopric appreciates your acceptance of a speaking assignment in Sacrament Meeting.
    The date and time of the meeting, the time for your talk, and the general topic for the talk are as follows:<br>
    <b>Date:</b> {{ object.date|date:"l, F d, Y" }}<br>
    <b>Topic:</b> {{ object.topic }}<br>
    <b>Time for your talk:</b> Please prepare to talk for approximately {{ object.time_range }} minutes.<br>
    {% if object.reference_materials %}
    <b>Additional References:</b> {{ object.reference_materials }}<br>
    {% endif %}
  </p>

  <p>
  We ask that you join us on the stand 5-10 minutes before the meeting begins to help set the tone of
  quiet reverence appropriate for Sacrament Meeting.
  </p>

  <p>
  It is our hope that each sacrament meeting is a spiritual experience for all who attend and is in
  harmony with the sacred nature of the sacrament. To help achieve this, we have been asked to
  counsel you as follows: “To teach the doctrines of the gospel, relate faith-promoting experiences,
  bear witness of divinely revealed truths, and use the scriptures (see D&C 42:12; 52:9). Speakers
  should teach in a spirit of love after prayerful preparation. They should not speak on subjects that
  are speculative, controversial, or out of harmony with Church doctrine.”
  </p>

  <p>
  If you have any questions or concerns, contact James McDonald at jlmcd76@gmail.com or by
  phone at (720) 587-9130. Thank you for accepting this speaking assignment. May the sustaining
  influence of our Heavenly Father be with you as you prepare and deliver your talk.
  </p>

  Sincerely,<br>
  The Broomfield 1st Ward Bishopric:<br>
  {{ object.bishopric|linebreaksbr  }}
</body>
</html>

events/templates/events/talk_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<img src="{% static 'images/179px-Logo_of_the_Church_of_Jesus_Christ_of_Latter-day_Saints.png' %}" class="center"><br>
<p class="helv">
  BROOMFIELD FIRST WARD<br>
  BOULDER COLORADO STAKE
</p>

<p>
  {{ object.created|date:"d F Y" }}
</p>

<p>
{{ object.speaker.full_name }}<br>
{{ object.speaker.street1 }}<br>
{% if object.speaker.street2 %}
{{ object.speaker.street2 }}<br>
{% endif %}
Broomfield, CO 80020
</p>
<br>

<p>
  <b>Date</b>: {{ object.date|date:"l, F d, Y" }}<br>
  {% if object.topic  %}
  <b>Topic</b>: {{ object.topic }}<br>
  {% endif %}
  {% if object.time_range  %}
  <b>Time for your talk</b>: Please prepare to talk for approximately {{ object.time_range }} minutes.<br>
  {% endif %}
  {% if object.reference_materials %}
  <b>Additional References:</b> {{ object.reference_materials }}<br>
  {% endif %}
</p>

<p>
  Sincerely,<br>
  The Broomfield 1st Ward Bishopric:<br>
  {{ object.bishopric|linebreaksbr  }}<br>
</p>

<a class="btn btn-primary" href="{% url 'talks:talk-pdf' id=object.pk%}">PDF</a>
<a class="btn btn-secondary" href="{% url 'talks:talk-edit' id=object.pk%}">Edit</a>

{% endblock %}

events/templates/events/talk_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Add Talk{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker.standalone.min.css" integrity="sha256-4PQp5wYKIGyIpShGiM2DG3LbiWuMtYl/y+uKY4EHHoc=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock %}

{% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"
        integrity="sha256-TueWqYu0G+lYIimeIcMI8x1m14QH/DQVt4s9m/uuhPw="
        crossorigin="anonymous">
</script>
<script>
$('.dateinput,.fa-calendar').datepicker({
    format: "dd M yyyy",
    daysOfWeekDisabled: "1,2,3,4,5,6",
    maxViewMode: 2,
    todayBtn: "linked",
    autoclose: true,
    todayHighlight: true,
    toggleActive: true
});
</script>
{% endblock %}

{% block content %}
  {% crispy form %}
{% endblock %}

events/templates/events/talk_list.html
{% extends "base.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
{% endblock %}

{% block javascript %}
<script>
  $('#talks').DataTable({
    "lengthMenu": [[15, 25, -1], [15, 25, "All"]]
  });

</script>
{% endblock %}

{% block content %}
    <h2>Talks</h2>
    <table id="talks" class="display" style="width:100%" data-page-length='15' data-order='[[ 3, "desc"], [2, "asc"]]'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Topic</th>
        <th>Order</th>
        <th>Date</th>
      </tr>
      </thead>
      <tbody>
      {% for talk in object_list %}
        <tr>
          <td>
            <a href="{{ talk.get_absolute_url }}">
              {{ talk.speaker.full_name }}
            </a>
          </td>
          <td>
            {% if talk.topic %}
            {{ talk.topic }}
            {% endif %}
          </td>
          <td>
            {% if talk.order %}
            {{ talk.order }}
            {% endif %}
          </td>
          <td>{{ talk.date|date:"Y-m-d" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}